---
roles:
  # https://galaxy.ansible.com/ui/standalone/roles/geerlingguy/swap/
  - src: geerlingguy.swap
    version: "2.1.0"

collections:
  - ansible.posix
  - community.docker
  - community.general
