---
- name: Ensure backports repository is set
  ansible.builtin.deb822_repository:
    name: "debian-backports"
    types: [deb, deb-src]
    uris: "http://deb.debian.org/debian"
    suites: "{{ ansible_facts['distribution_release'] }}-backports"
    components: main
    signed_by: "/usr/share/keyrings/debian-archive-keyring.gpg"
    install_python_debian: true
    state: present
  when: ansible_facts['distribution'] == "Debian"
  notify: apt update

- name: Ensure handlers are notified immediately to update the apt cache
  ansible.builtin.meta: flush_handlers

- name: Ensure apt cache and packages are updated
  apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
  register: _progress_status
  until: _progress_status is succeeded
  delay: 5
  retries: 5
  changed_when: false

- name: Upgrade all packages
  apt:
    upgrade: dist
    force_apt_get: true
  register: _progress_status
  until: _progress_status is succeeded
  delay: 5
  retries: 5
  when: packages_upgrade_all | bool
