---
- name: Check if swap file exists
  stat:
    path: "{{ swap_file_path }}"
  register: _swap_file_check

- name: Determine if the swap file needs to be (re)created
  set_fact:
    _swap_file_outdated: "{{ not _swap_file_check.stat.exists or (_swap_file_check.stat.size // 1048576) != swap_size }}"

- name: Replace outdated swap file
  when:
    - _swap_file_check.stat.exists
    - _swap_file_outdated | bool
  block:
    - name: Turn off swap file
      command: "swapoff {{ swap_file_path }}"

    - name: Remove outdated swap file
      file:
        path: "{{ swap_file_path }}"
        state: absent

- name: Create swap file
  command: "dd if=/dev/zero of={{ swap_file_path }} count={{ swap_size }} bs=1MiB"
  when: _swap_file_outdated | bool

- name: Protect swap file
  file:
    path: "{{ swap_file_path }}"
    owner: "root"
    group: "root"
    mode: "0600"

- name: Format swap file
  command: "mkswap {{ swap_file_path }}"
  when: _swap_file_outdated | bool

- name: Write swap entry in fstab
  ansible.posix.mount:
    path: "swap"
    src: "{{ swap_file_path }}"
    fstype: "swap"
    opts: "sw"
    passno: 0
    dump: 0
    state: present

- name: Turn on swap
  command: "swapon -a"
  changed_when: false

- name: Set swap swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness_value }}"
    state: present
    reload: true
