---
# This task configures sudo to prompt users for the root password
# instead of their own when executing commands with elevated privileges.
# This enhances security by restricting sudo access to those who know the root password.
- name: Restrict sudo access to root password
  lineinfile:
    path: "/etc/sudoers"
    regexp: "^Defaults\\s+rootpw\\b"
    line: "Defaults rootpw"
    validate: "visudo -cf %s"

- name: Change timezone
  community.general.timezone:
    name: "{{ system_timezone }}"

- name: Add /etc/timezone file
  copy:
    content: "{{ system_timezone }}"
    dest: "/etc/timezone"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Ensure required locale exists
  community.general.locale_gen:
    name: "{{ system_locale }}"
    state: present
  when: ansible_facts['distribution'] == "Debian"

- name: Ensure systemd-logind service is in the right state
  systemd:
    name: systemd-logind
    state: started

- name: Set locale
  shell: "localectl set-locale LANG={{ system_locale }}"
  args:
    executable: /bin/bash
  changed_when: false

- name: Protect toolchain binaries
  file:
    path: "/usr/bin/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0700"
  loop:
    - as
    - gcc
    - cc
    - g++
    - c++
    - cpp
    - gcc-ar
    - gcc-nm
    - gcc-ranlib
    - ld
    - ld.bfd
    - ld.gold
  failed_when: false
