---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Include the role
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        swap_configure: false
        packages_upgrade_all: false
        packages_extra: false
        system_root_user_password: "Test-Pa$$w0rd123456"
